branch-defaults:
  default:
    environment: null
    group_suffix: null
global:
  application_name: first-try
  branch: null
  default_ec2_keyname: first-try-keypair
  default_platform: Node.js 20 running on 64bit Amazon Linux 2023
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
